In [1]:
import pandas as pd 
import numpy as np

In [2]:
df1 = pd.read_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1/MCF7_AZD_normalized_counts.csv', index_col=0)

df2 = pd.read_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1_py/MCF7_AZD_normalized_counts.csv', index_col=0)

FileNotFoundError: [Errno 2] No such file or directory: '/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1/MCF7_AZD_normalized_counts.csv'

In [3]:
df3 = pd.read_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1_numeric/MCF7_AZD_normalized_counts.csv')
df4 = pd.read_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1_py_numeric/MCF7_AZD_normalized_counts.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/home/hanna/Desktop/RnD/toxicology/toxicology_modules/claude_test1_numeric/MCF7_AZD_normalized_counts.csv'

In [17]:
annot = pd.read_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/DEG_modules/BIOS2931_deg_annot.csv')
annot['dose']= annot['dose'].str.replace('0p1uM','0.1').str.replace('10uM','10').str.replace('1uM','1')
annot['dose']=annot['dose'].astype('float')
annot.to_csv('/home/hanna/Desktop/RnD/toxicology/toxicology_modules/DEG_modules/BIOS2931_deg_annot_numeric.csv')
annot

          sample_name sample compound  dose  replicate
0    MCF7_AZD_0p1uM-1   MCF7      AZD   0.1          1
1    MCF7_AZD_0p1uM-2   MCF7      AZD   0.1          2
2    MCF7_AZD_0p1uM-3   MCF7      AZD   0.1          3
3     MCF7_AZD_10uM-1   MCF7      AZD  10.0          1
4     MCF7_AZD_10uM-2   MCF7      AZD  10.0          2
..                ...    ...      ...   ...        ...
244   MDA_ZOTA_10uM-2    MDA     ZOTA  10.0          2
245   MDA_ZOTA_10uM-3    MDA     ZOTA  10.0          3
246    MDA_ZOTA_1uM-1    MDA     ZOTA   1.0          1
247    MDA_ZOTA_1uM-2    MDA     ZOTA   1.0          2
248    MDA_ZOTA_1uM-3    MDA     ZOTA   1.0          3

[249 rows x 5 columns]

In [8]:
df3 = round(df3, 5)
df4 = round(df4, 5)

In [5]:
df3

,gene,dose,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,A2M_1,0.1,0.00000,NaN,NaN,NaN,NaN,NaN
1,AAMP_2,0.1,945.81178,0.22337,0.22762,0.98134,0.32642,0.62852
2,AARS1_3,0.1,747.61523,-0.36252,0.33075,-1.09605,0.27306,0.58285
3,AATF_4,0.1,18.74313,-0.28853,0.50739,-0.56866,0.56959,0.80858
4,ABCB1_12,0.1,14.79823,0.45607,0.38524,1.18386,0.23647,0.54599
...,...,...,...,...,...,...,...,...
67594,RPL7_92861,10.0,2.27149,1.50474,0.89982,1.67227,0.09447,0.28954
67595,RPL4_93059,10.0,9.18008,-1.19707,0.64243,-1.86336,0.06241,0.23249
67596,GNG10_93243,10.0,0.71784,-0.05721,1.90633,-0.03001,0.97606,NaN
67597,ACOT1_93339,10.0,0.38156,-1.23764,2.91789,-0.42416,0.67145,NaN
67598,HDAC5_93392,10.0,365.84684,0.65434,0.30008,2.18052,0.02922,0.15128

In [6]:
df4

,gene,dose,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,A2M_1,0.1,0.00000,NaN,NaN,NaN,NaN,NaN
1,AAMP_2,0.1,945.81178,0.22337,0.22759,0.98146,0.32636,0.62380
2,AARS1_3,0.1,747.61523,-0.36252,0.33069,-1.09627,0.27296,0.57714
3,AATF_4,0.1,18.74313,-0.28854,0.50746,-0.56859,0.56963,0.80592
4,ABCB1_12,0.1,14.79823,0.45608,0.38541,1.18337,0.23666,0.54040
...,...,...,...,...,...,...,...,...
67594,RPL7_92861,1.0,2.27149,-1.05072,1.17736,-0.89244,0.37216,NaN
67595,RPL4_93059,1.0,9.18008,-0.59093,0.60371,-0.97882,0.32767,0.55916
67596,GNG10_93243,1.0,0.71784,1.59414,1.70365,0.93572,0.34942,NaN
67597,ACOT1_93339,1.0,0.38156,0.61752,2.88409,0.21411,0.83046,NaN
67598,HDAC5_93392,1.0,365.84684,0.79278,0.29981,2.64426,0.00819,0.05820

In [9]:
(df3==df4).all().all()

True